#!/bin/bash

# specify the case you want to test here!
case=case3
casepertama=case1
casekedua=case2
version=basic
# Build and run your final project!
NTHU_bike:
	g++ -g -std=c++11 -o ./bin/main ./src/*.cpp
	./bin/main $(casepertama) $(version)
	./bin/main $(casekedua) $(version)
	./bin/main $(case) $(version)